apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-webapp
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dp-webapp
  # Минимум 2 пода - чтобы обеспечивать отказоустойчивость, 4 пода - для пиков
  minReplicas: 2
  maxReplicas: 4
  behavior:
    # Поведение при масштабировании вверх
    scaleUp:
      stabilizationWindowSeconds: 30
      selectPolicy: Max
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
    # Поведение при масштабировании вниз
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Min
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
  # Метрика, по которой масштабируется - загрузка CPU
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70